# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  This course is a study of the layers of abstraction composing the design of modern computing systems. Topics include numeric representation, digital logic, CPU design, machine and assembly language, the program stack, virtual machines, compilers, assemblers, memory management and device drivers.
baseurl: "/csci322" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 322
title: Computing Systems Organization
semester: Spring 2022

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: Calendar
    url: '#calendar'
  - title: Coursework and policies
    subfolderitems:
      - page: Due dates policy
        url: '#deadlines'
      - page: Projects
        url: '#projects'
      - page: Grading
        url: '#grading'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: yorgey
    name: Dr. Brent Yorgey
    email: yorgey@hendrix.edu
    web: http://ozark.hendrix.edu/~yorgey
    phone: (501) 450-1377
    officehours: https://byorgey.youcanbook.me

offerings:
  - name: LECTURE 01
    loc: MCREY 315
    time: TR 9:45am - 11:00am (B2)
    instructor: yorgey

resources:
  - name: From Nand to Tetris
    image: assets/images/n2t-logo.png
    url: https://www.nand2tetris.org/
  - name: The Elements of Computing Systems,<br/> 2nd ed. (or 1st)
    image: assets/images/teocs.jpg
    url: https://www.amazon.com/Elements-Computing-Systems-second-Principles/dp/0262539802/

# Build settings
markdown: kramdown
plugins:
# - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
